[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SMONSTER_DOC"
authors = [{name = "Franck Elisabeth", email = "none"}]
dynamic = ["version", "description"]
